classDiagram
class Loan {
    - id
    - book
    - user
    - dueDate
    - retriveDate
    - LoanDate

    + loan(book, user, dueDate, retiveDate, loanDate)
    + renew(Book, user, dueDate)
    + return(bokk, user)
    + isOverDue(book, user, )
}